title: Matheus Leal
# subtitle: Página Matheus Leal
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://matheuslealaquino.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /about/
    - text: Blog
      url: /blog/
    # - text: Projetos
    #   url : /projetos/
    # - text: Shop
    #   url : /shop/
    # - text: Entre em contato
    #  url : /contact/
    - text: Styleguide
      url: /styleguide/
    
# Edit these details 

author_logo: matheus.jpg
author: Matheus Leal
author_bio: Aluno de Sistemas de Informação na Universidade Federal Fluminense. Trabalho como desenvolvedor full-stack, criando sites e aplicativos para Android e IOS.
author_email: "matheusleal.a@gmail.com"
author_location: Brasil
author_website_url: "https://matheuslealaquino.github.io"

author_work_experiences:
  - company_name: EDCOM CONSULTORIA
    company_logo: edcom.png
    time: dez de 2018 – o momento
    company_url: https://www.edcom.com.br/
    designation: Desenvolvedor Web - Full Stack 
    description: '- Desenvolvimento e manutenção de sistemas web: <br>
                  <ul>
                    <li>PHP</li>
                    <li>NodeJS</li>
                    <li>C#</li>
                    <li>MySQL</li>
                    <li>SQL Server</li>
                    <li>Docker</li>
                    <li>Vue.Js: Bootstrap-Vue e Quasar Framework</li>
                    <li>Bootstrap</li>
                    <li>Wordpress</li>
                  </ul>'
    visibility: true 
  - company_name: EDCOM CONSULTORIA
    # company_logo: edcom.png
    time: jun de 2018 – nov de 2018
    company_url: https://www.edcom.com.br/
    designation: Estágio - Desenvolvedor Web - Full Stack 
    description: '- Desenvolvimento e manutenção de sistemas web: <br>
                  <ul>
                    <li>PHP</li>
                    <li>C#</li>
                    <li>NodeJS</li>
                    <li>MySQL</li>
                    <li>SQL Server</li>
                    <li>Bootstrap</li>
                    <li>Wordpress</li>
                  </ul>'
    visibility: true
  - company_name: STI UFF - Superintendência de Tecnologia da Informação
    company_logo: sti.png
    time: nov de 2017 – jun de 2018
    company_url: http://www.uff.br/sti
    designation: Estágio - Desenvolvedor Java
    description: '- Desenvolvimento e manutenção de aplicações Java utilizando: <br> 
      <ul>
        <li>Spring Boot</li>
        <li>JSP</li>
        <li>Oracle Database</li>
        <li>Docker</li>
        <li>Bootstrap</li>
        <li>JQuery</li>
      </ul>'
    visibility: true
  - company_name: Coordenação de Educação a Distância
    company_logo: logocead.png
    time: jan de 2017 – nov de 2017
    company_url: http://www.cead.uff.br/site/
    designation: Estágio - Desenvolvedor Web
    description: '- Criação de sites utilizando: <br>
      <ul>
        <li>Bootstrap</li>
        <li>JQuery</li>
        <li>PHP</li>
        <li>MySQL</li>
        <li>Wordpress</li>
      </ul>
      - Gerenciamento da plataforma Moodle. <br> - Suporte aos usuários da plataforma Moodle.'
    visibility: true

author_education_details:
  - college_logo: uff.png
    college_name: Universidade Federal Fluminense
    college_url: http://uff.br/
    college_degree: Sistemas de Informação
    description: Bacharel em Sistemas de Informação
    visibility: true

author_project_details:
  - project_thumbnail: gamershub.png
    project_title: Gamers Hub
    project_description: A Platform built for Gamers and Game Devs
    project_url: https://gamershub.in
    visibility: true
  - project_thumbnail: programmingebooks.png
    project_title: Programming Ebooks
    project_description: A Platform to easily find and read programming books
    project_url: https://programmingebooks.com
    visibility: true

author_certificate_details:
  - certificate_thumbnail: udemy.png
    certificate_title: Vue JS 2.0 - Mastering Web Apps
    certificate_url: https://www.udemy.com/certificate/UC-L6LFQ3PP/
    visibility: true
  - certificate_thumbnail: udemy.png
    certificate_title: 'Curso online Git Completo: Do básico ao avançado' 
    certificate_url: https://www.udemy.com/certificate/UC-EUQHX5R7/
    visibility: true

# social links
# twitter_username: johndoe
github_username:  MatheusLealAquino
# facebook_username: johndoe
linkedin_username: matheus-leal
# behance_username: johndoe
instagram_username: matheusleal_a
# medium_username: johndoe
telegram_username: MatheusLealA
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments using disqus
# disqus_shortname: sujay-kundu  

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# formspree (contact form)
# formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
# google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false
show_author_certificates: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
